apiVersion: 1
datasources:
  - name: OpenGrid MySQL
    uid: opengrid-mysql
    type: mysql
    url: mysql:3306
    user: grafana
    jsonData:
      database: open_grid_loss
      maxOpenConns: 5
      timezone: '+00:00'
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
